import { AnalyticsProvider } from "@/components/analytics-provider";
import type { Metadata } from "next";
import type { ReactNode } from "react";
import "./globals.css";

const siteUrl = "https://india-standards.significanthobbies.com";
const title = "India Standards — PLFS demographic calculator";
const description =
  "Estimate how many Indian adults match selected demographic standards using aggregate PLFS 2025 data, with a visible 95% uncertainty range and source limits.";
const socialImage =
  "https://raw.githubusercontent.com/Significant-Hobbies/india-standards/main/artifacts/design/review/after-1440.png";
const structuredData = {
  "@context": "https://schema.org",
  "@type": "WebApplication",
  name: "India Standards",
  applicationCategory: "LifestyleApplication",
  operatingSystem: "Web",
  url: siteUrl,
  image: socialImage,
  description,
  sameAs: ["https://github.com/Significant-Hobbies/india-standards"],
};

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title,
  description,
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    siteName: "India Standards",
    url: "/",
    title,
    description,
    images: [
      {
        url: socialImage,
        alt: "India Standards demographic calculator workbench",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title,
    description,
    images: [socialImage],
  },
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/* fleet-jsonld:start (generated by apply-agent-surfaces; edit registry, not this) */}
        <script
          type="application/ld+json"
          // biome-ignore lint/security/noDangerouslySetInnerHtml: fleet-generated JSON-LD
          dangerouslySetInnerHTML={{
            __html: `{"@context":"https://schema.org","@graph":[{"@type":"Person","@id":"https://sarthakagrawal.dev/#person","name":"Sarthak Agrawal","jobTitle":"AI Infrastructure & Product Engineer","url":"https://sarthakagrawal.dev","image":"https://avatars.githubusercontent.com/u/43884471?v=4","sameAs":["https://sarthakagrawal.dev","https://www.linkedin.com/in/sarthakagrawal927","https://github.com/sarthakagrawal927","https://x.com/sarthakcodes","https://huggingface.co/sarthakagrawal927"],"knowsAbout":["AI infrastructure","Local-first software","Post-training language models","AI code review","Cloudflare Workers","TypeScript","Rust"],"affiliation":{"@type":"Organization","@id":"https://sassmaker.com/#app","name":"SaaS Maker","url":"https://sassmaker.com"}},{"@type":"WebSite","@id":"https://india-standards.significanthobbies.com/#app","name":"India Standards","url":"https://india-standards.significanthobbies.com","description":"Evidence-bounded demographic standards calculator using aggregate Indian survey data.","publisher":{"@id":"https://sarthakagrawal.dev/#person"},"sameAs":["https://github.com/Significant-Hobbies/india-standards"]}]}`,
          }}
        />
        {/* fleet-jsonld:end */}
        {/* Microsoft Clarity — session replay + heatmaps (additive; PostHog stays) */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(c,l,a,r,i,t,y){c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/y6btzgl5r3";y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);})(window,document,"clarity","script","y6btzgl5r3");window.clarity("set","project_id","india-standards");`,
          }}
        />
      </head>
      <body>
        <AnalyticsProvider>{children}</AnalyticsProvider>
        <script
          src="https://sassmaker.com/project-strip.js"
          data-project="india-standards"
          defer
        />
        <script
          src="https://sassmaker.com/ai-chat-footer.js"
          data-name="India Standards"
          defer
        />
      </body>
    </html>
  );
}
